### ISSUE TITLE
custom base url support

### ISSUE THREAD

**Issue by StoneShiLei** [UBOS-tech/node-red-contrib-openai-ubos#1]
Hello, I come from a region where OpenAI services cannot be used, but there are people here who provide proxy services. The domain name of their provided interface is different from that of OpenAI, so I wonder if you could provide a version that exposes the BaseAPI? Thank you.

**Comment by vovajr11** [comment]
Hi) you want to add a custom url?
For example msg.url = "https://yourapi.com/v1/images/generations"
